apiVersion: v1
kind: ConfigMap
metadata:
  name: local-storage-scheduler-config
  namespace: local-storage-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: local-storage-scheduler
    leaderElection:
      leaderElect: true
      lockObjectName: local-storage-scheduler
    clientConnection:
      kubeconfig: /etc/kubernetes/scheduler.conf 
    plugins:
      filter:
        enabled:
        - name: dlocal-scheduler-plugin
      score:
        enabled:
        - name: dlocal-scheduler-plugin

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-storage-scheduler
  namespace: local-storage-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-storage-scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: local-storage-scheduler
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      containers:
      - command:
        - kube-scheduler
        - -v=2
        - --bind-address=0.0.0.0
        - --kubeconfig=/etc/kubernetes/scheduler.conf
        - --scheduler-name=local-storage-scheduler
        - --leader-elect=false
        - --leader-elect-resource-name=local-storage-scheduler
        - --config=/etc/localstorage/scheduler-config.yaml
        - --leader-elect-resource-namespace=local-storage-system  
        image: hwameistor/scheduler:v0.0.1
        imagePullPolicy: IfNotPresent
        name: local-storage-scheduler
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubernetes/scheduler.conf
          name: kubeconfig
          readOnly: true
        - mountPath: /etc/localstorage/
          name: local-storage-scheduler-config
          readOnly: true
      volumes:
      - hostPath:
          path: /etc/kubernetes/admin.conf
          type: FileOrCreate
        name: kubeconfig
      - configMap:
          name: local-storage-scheduler-config
          items:
          - key: scheduler-config.yaml
            path: scheduler-config.yaml
        name: local-storage-scheduler-config
      serviceAccountName: storage-admin
      serviceAccount: storage-admin
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        operator: Exists