name: Period check
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  period-check-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Unit test
        run: make unit-test
  period-check-e2e-test:
    runs-on: ["self-hosted"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: e2e test
        run: make e2e-test
