name: HwameiStor pr

on:
  pull_request:
    branches:
      - main

jobs:
  pull_request-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: unit-test
        run: make unit-test
  pull_request-e2e-test:
    #    runs-on: ["self-hosted"]
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set env
        run: |
          echo "GOVC_USERNAME=`echo ${{ secrets.GOVC_USERNAME }}`" >> $GITHUB_ENV
          echo "GOVC_PASSWORD=`echo ${{ secrets.GOVC_PASSWORD }}`" >> $GITHUB_ENV
          echo "GOVC_URL=`echo ${{ secrets.GOVC_URL }}`" >> $GITHUB_ENV
          echo "GOVC_DATACENTER=`echo ${{ secrets.GOVC_DATACENTER }}`" >> $GITHUB_ENV
      - name: e2e-test
        run: |
          echo "Uname: ${GOVC_USERNAME}"
          echo "PWD: ${GOVC_PASSWORD}"
          echo "Raw: ${{ secrets.GITHUB_TOKEN }}"
          make e2e-test
